title: "Michael Shoemaker — Data Engineering"
description: "Modern, production-like data engineering projects with concise walkthroughs."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Michael Shoemaker"
github_username: "YOUR_GITHUB_USERNAME"
youtube_channel: "YOUR_YOUTUBE_CHANNEL_ID_OR_HANDLE"
medium_username: "YOUR_MEDIUM_USERNAME"
exclude:
  - README.md
